In [54]:
import numpy as np


## 1,i)

In [55]:
A = np.array([[2,2,3], [-2,7,4], [-3,-3,-4], [-8,2,3]])
print(A)

[[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]
 [-8  2  3]]


B = np.array([[4], [3], [3], [2]])
new_matrix = np.hstack((A,B))
print(new_matrix)

In [57]:
determinant = np.linalg.det(new_matrix)
determinant

np.float64(-1078.0000000000005)

## ii)

In [58]:
A = np.array([[2,2,3], [-2,7,4], [-3,-3,-4], [-8,2,3]])
reduced_matrix = np.delete(A,0, axis = 0)
print(reduced_matrix)

[[-2  7  4]
 [-3 -3 -4]
 [-8  2  3]]


In [59]:
determinant = np.linalg.det(reduced_matrix)
determinant

np.float64(169.0)

## iii)

In [60]:
#A is the matrix then AT is Transpose
A = np.array([[2,2,3], [-2,7,4], [-3,-3,-4], [-8,2,3]])
transposeAT = np.transpose(A)
transposeAT

array([[ 2, -2, -3, -8],
       [ 2,  7, -3,  2],
       [ 3,  4, -4,  3]])

In [61]:
print(A)

[[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]
 [-8  2  3]]


In [62]:
multiplied_matrix = np.dot( A, transposeAT )
multiplied_matrix

array([[ 17,  22, -24,  -3],
       [ 22,  69, -31,  42],
       [-24, -31,  34,   6],
       [ -3,  42,   6,  77]])

In [63]:
determinant = np.linalg.det(multiplied_matrix)
determinant

np.float64(-2.7018387527277813e-11)

In [64]:
# Yes, AAt is Invertable because it's determinant is not zero

In [65]:
multiplied_matrix = np.dot( transpose, A )
multiplied_matrix

ValueError: shapes (3,) and (4,3) not aligned: 3 (dim 0) != 4 (dim 0)

In [66]:
determinant = np.linalg.det(multiplied_matrix)
determinant

np.float64(-2.7018387527277813e-11)

In [67]:
# Yes it is invertible because the detreminant is not zero

## 2. i)

In [68]:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [69]:
its_shape = np.shape(X)
print(its_shape)

(3, 2)


## ii)

In [70]:
transpose = np.transpose(X)
transpose

array([[25,  5,  3],
       [ 2, 26,  7]])

## iii)

In [71]:
scarler_X = np.dot(3,X)
scarler_X

array([[75,  6],
       [15, 78],
       [ 9, 21]])

## iv)

In [72]:
A = ([[3, 4], [5, 6], [7, 8]])
A

[[3, 4], [5, 6], [7, 8]]

In [73]:
# we use X's transpose to get the value of XA
transpose_X = np.transpose(X)
transpose_X

array([[25,  5,  3],
       [ 2, 26,  7]])

In [74]:
multiplied_matrix = np.dot(A,transpose_X)
multiplied_matrix

array([[ 83, 119,  37],
       [137, 181,  57],
       [191, 243,  77]])

In [75]:
# Approach 2
#Multiplying A and X dirrect

In [76]:
matrix_multiplied = A*X
matrix_multiplied

array([[ 75,   8],
       [ 25, 156],
       [ 21,  56]])

## V)

In [77]:
inverse = np.linalg.inv(multiplied_matrix)
inverse
# we have used multiplied_matrix because A and X are square matrices that cant get inverse

array([[-1.89116000e+13,  3.78232000e+13, -1.89116000e+13],
       [-7.43269860e+13,  1.48653972e+14, -7.43269860e+13],
       [ 2.81474977e+14, -5.62949953e+14,  2.81474977e+14]])

## 3, i)

In [78]:
entries = [25, 2, 5]
entries


[25, 2, 5]

In [79]:
p = np.array(entries)
p

array([25,  2,  5])

## ii)

In [80]:
its_shape = np.shape(entries)
its_shape

(3,)

## iii)

In [81]:
transpose = np.transpose(entries)
transpose

array([25,  2,  5])

## iv)

In [82]:
norm_p = np.linalg.norm(entries)
norm_p

np.float64(25.573423705088842)