In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

## MATRICES

## Create a 2*2 matrix

In [23]:
matrix_1 = np.array([[2,1],[3,4]])
print(matrix_1)

[[2 1]
 [3 4]]


## Creat a 3*3

In [24]:
matrix_2 = np.array([[3,1,4],[2,1,3],[5,2,4]])
print(matrix_2)

[[3 1 4]
 [2 1 3]
 [5 2 4]]


## Addition of matrices

In [9]:
x = np.array([[2,1],[3,4]])
y = np.array([[1,8],[3,4]])
print(np.add(x,y))

[[3 9]
 [6 8]]


## Subtraction of Matrices

In [11]:
x = np.array([[2,1],[3,4]])
y = np.array([[1,8],[3,4]])
print(np.subtract(x,y))

[[ 1 -7]
 [ 0  0]]


## Multiplication of Matrices


In [29]:
#using multiply. This multiplies direct

x = np.array([[2,1],[3,4]])
y = np.array([[1,8],[3,4]])
print(np.multiply(x,y))

[[ 2  8]
 [ 9 16]]


In [30]:
# using dot. this multiplies manually like we do in our books

x = np.array([[2,1],[3,4]])
y = np.array([[1,8],[3,4]])
print(np.dot(x,y))

[[ 5 20]
 [15 40]]


## Division of Matrices

In [13]:
x = np.array([[2,1],[3,4]])
y = np.array([[1,8],[3,4]])
print(np.divide(x,y))

[[2.    0.125]
 [1.    1.   ]]


## Transpose

In [16]:
x = np.array([[2,1],[3,4]])
print(x)

[[2 1]
 [3 4]]


In [17]:
transpose_x = np.transpose(x)
print(transpose_x)

[[2 3]
 [1 4]]


## Determinant

In [18]:
x = np.array([[2,1],[3,4]])
print(x)

[[2 1]
 [3 4]]


In [22]:
determinant_x = np.linalg.det(x)
determinant_x

np.float64(5.000000000000001)