# creating a two by two matrix

In [1]:
import numpy as np

In [2]:
matrix_A=np.array([[2,1],[3,4]])
print(matrix_A)

[[2 1]
 [3 4]]


# creating a 3x3 matix

In [4]:
matrix_B=np.array([[3,1,4],[2,1,3],[5,2,4]])
print(matrix_B)

[[3 1 4]
 [2 1 3]
 [5 2 4]]


# Addition of matrices

In [6]:
x=np.array([[2,3,5],[4,5,6],[7,4,2]])
y=np.array([[1,2,3],[8,9,7],[6,5,3]])
print(np.add(x,y))

[[ 3  5  8]
 [12 14 13]
 [13  9  5]]


In [7]:
x=np.array([[2,3,5],[4,5,6],[7,4,2]])
y=np.array([[1,2,3],[8,9,7],[6,5,3]])
print(np.subtract(x,y))

[[ 1  1  2]
 [-4 -4 -1]
 [ 1 -1 -1]]


In [8]:
x=np.array([[2,3,5],[4,5,6],[7,4,2]])
y=np.array([[1,2,3],[8,9,7],[6,5,3]])
print(np.dot(x,y))

[[56 56 42]
 [80 83 65]
 [51 60 55]]


In [9]:
x=np.array([[2,3,5],[4,5,6],[7,4,2]])
y=np.array([[1,2,3],[8,9,7],[6,5,3]])
print(np.divide(x,y))

[[2.         1.5        1.66666667]
 [0.5        0.55555556 0.85714286]
 [1.16666667 0.8        0.66666667]]


In [10]:
x=np.array([[2,3,5],[4,5,6],[7,4,2]])
y=np.array([[1,2,3],[8,9,7],[6,5,3]])
print(np.multiply(x,y))

[[ 2  6 15]
 [32 45 42]
 [42 20  6]]


In [12]:
B=np.array([[3,5],[6,7]])
print(np.transpose(B))

[[3 6]
 [5 7]]


In [14]:
T=B.T
print(T)

[[3 6]
 [5 7]]


# Determinant of a matrix

In [15]:
x=np.array([[3,6],[7,8]])
determinant=np.linalg.det(x)
print(determinant)

-17.999999999999996


# multiplication

In [18]:
d=np.array([[7,2],[1,3]])
print(np.dot(d,x))

[[35 58]
 [24 30]]
