2024/DSC/0056/SS

In [63]:
import numpy as np   #importing numpy

In [64]:
import pandas as pd   # importing pandas

In [65]:
import matplotlib as plt    #importing matplotlib

In [66]:
dct={
   'fruit':['apple','banana','cherry'],
    'value':[1,2.0,3]
}
#creating a dictionary

In [67]:
dic = pd.DataFrame(data=dct)    #transforming into a dataframe

In [68]:
dic

fruit  value
0   apple    1.0
1  banana    2.0
2  cherry    3.0

In [69]:
array={'elements':[10,20,30,40] }   #an array

In [86]:
array=pd.DataFrame(data=array)

In [87]:
elements_mean=array['elements'].mean()


In [88]:
elements_mean

np.float64(25.0)

In [92]:
elements_median=array['elements'].median()

In [93]:
elements_median

np.float64(25.0)

In [94]:
elements_max=array['elements'].max()


In [95]:
elements_max

np.int64(40)

In [96]:
elements_min=array['elements'].min()

In [98]:
elements_min

np.int64(10)

LINEAR PLOTING

In [102]:
data={'x':[1,2,3,4],
      'y1':[1,4,2,3],
       'y2':[2,3,4,5],
}

In [1]:
import numpy as np

In [5]:
arr = np.array ([1,2,3,4,5])
print(arr)
print (type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
apr = np.array (['masha','violet', 'babra', 'gift'])
print(apr)
print(type(apr))

['masha' 'violet' 'babra' 'gift']
<class 'numpy.ndarray'>


In [7]:
import numpy as np
print (np.__version__)

2.1.1


In [9]:
arr = np.array((1,2, 3,4 ,5))
print (arr)
print (type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
arr = np.array(42) # 0-d arrays
print (arr)

42


In [2]:
import numpy as np

In [3]:
arr = np.array ([1,2,3,4,5])
print (arr)       #1-d arrays      # d means dimension

[1 2 3 4 5]


In [5]:
# to check the number of dimensions syntax =ndim
import numpy as np
a=np.array(42)
b= np.array([1,2,3,4,5])
c=np.array([[1,2,3],[2,3,4]])
print(a.ndim,b.ndim,c.ndim)

0 1 2


In [18]:
dic ={
    'fruit':['apple',1,'banana',2.0,'cherry','iii']
}
print (dic)

{'fruit': ['apple', 1, 'banana', 2.0, 'cherry', 'iii']}


In [19]:
print(len(dic))

1


In [22]:
x=dic.get('fruit')
print(x)

['apple', 1, 'banana', 2.0, 'cherry', 'iii']
