In [19]:
import numpy as np
 

### create a 5x3 and 3x2  

In [20]:
A = np.array([[1,2,3],[1,4,5],[2,0,2],[4,0,2],[7,1,2]])
print(A)

[[1 2 3]
 [1 4 5]
 [2 0 2]
 [4 0 2]
 [7 1 2]]


In [21]:
B = np.array([[1,2],[1,3],[4,1]])
print(B)

[[1 2]
 [1 3]
 [4 1]]


In [22]:
multiply = np.dot(A,B)
print(multiply)

[[15 11]
 [25 19]
 [10  6]
 [12 10]
 [16 19]]


## identity matrix of 3x3

In [23]:
x = np.array([[0,1,0],[1,0,1],[0,1,0]])
print(x)

[[0 1 0]
 [1 0 1]
 [0 1 0]]


In [24]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
vectornull = np.zeros(10)
print(vectornull)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [26]:
from numpy import random
x = random.normal(size=(3,3,3))
print(x)

[[[-0.59334057 -0.61710648 -0.07181854]
  [-0.00889485 -0.48641006 -0.07758621]
  [ 0.0288197  -0.52620045 -1.81455325]]

 [[ 0.87868727 -0.12541437  0.08481475]
  [ 1.99508464 -0.00367135  0.13690067]
  [ 0.68204678  0.30890708 -0.55344563]]

 [[ 0.48553523 -0.33953146 -1.07152231]
  [ 0.5485173   0.47574155 -0.12269562]
  [ 1.35522967 -0.25849059 -1.65672397]]]


## create 5x5 matrix with values 1,2,3,4 just below the diagonal

In [39]:
matrix = np.zeros((5,5),dtype=int)

In [40]:
mattrix = np.fill_diagonal(matrix[1:], [1, 2, 3, 4])
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## normalise a 5x5 random matrix 

In [41]:
from numpy import  random
x = random.normal(size =(5,5))
print(x)

[[ 1.60655351 -0.39679244 -1.04247995 -0.73414401  0.18507591]
 [ 0.65697996  0.70489508 -0.06480012  1.26544836 -0.321124  ]
 [ 1.19333615 -0.89573999  1.27941022  0.05838486 -1.48918295]
 [-0.86691872 -0.53442822 -1.69075582 -0.29966942  0.02283518]
 [-0.15321282 -0.5550865  -0.76157051 -0.10501857  0.99268662]]


## How to  get the dates of yesterday, today and tomorrow

In [42]:
import numpy as np

In [43]:
today = np.datetime64('today','D')
print(today)

2024-12-09


In [44]:
yesterday = today-np.timedelta64(1,'D')
print(yesterday)

2024-12-08


In [45]:
tomorrow = today + np.timedelta64(1,'D')
print(tomorrow)

2024-12-10


## find indices of none zero elements from [1,2,0,0,4,0] 

In [46]:
import numpy as np
x= np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(x)
print( non_zero_indices[0])


[0 1 4]


In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Advertising.csv')
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]